// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrafficFineApp.Data;

#nullable disable

namespace trafficFineManager.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260824000040_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("trafficFineManager.Entities.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "StandartKullanici"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Yonetici"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Finansman"
                        });
                });

            modelBuilder.Entity("trafficFineManager.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IdentityNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "ahmet@test.com",
                            FirstName = "Ahmet",
                            IdentityNumber = "11111111111",
                            LastName = "StandartKullanici",
                            PasswordHash = "123456",
                            RegistrationNumber = "S-001",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            Email = "ayse@test.com",
                            FirstName = "Ayşe",
                            IdentityNumber = "22222222222",
                            LastName = "Yönetici",
                            PasswordHash = "123456",
                            RegistrationNumber = "S-002",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 3,
                            Email = "fatma@test.com",
                            FirstName = "Fatma",
                            IdentityNumber = "33333333333",
                            LastName = "Finans",
                            PasswordHash = "123456",
                            RegistrationNumber = "S-003",
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("trafficFineManager.Entities.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Brands");
                });

            modelBuilder.Entity("trafficFineManager.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "İstanbul"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Ankara"
                        });
                });

            modelBuilder.Entity("trafficFineManager.Entities.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Districts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            Name = "Kadıköy"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 1,
                            Name = "Beşiktaş"
                        },
                        new
                        {
                            Id = 3,
                            CityId = 1,
                            Name = "Şişli"
                        },
                        new
                        {
                            Id = 4,
                            CityId = 2,
                            Name = "Çankaya"
                        },
                        new
                        {
                            Id = 5,
                            CityId = 2,
                            Name = "Yenimahalle"
                        });
                });

            modelBuilder.Entity("trafficFineManager.Entities.FineType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ArticleNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("FineTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 1506.00m,
                            ArticleNumber = "47/1-b",
                            Description = "Kırmızı ışık kuralına uymamak",
                            IsActive = true
                        },
                        new
                        {
                            Id = 2,
                            Amount = 1506.00m,
                            ArticleNumber = "51/2-a",
                            Description = "Hız sınırını %10'dan %30'a kadar aşmak",
                            IsActive = true
                        },
                        new
                        {
                            Id = 3,
                            Amount = 3135.00m,
                            ArticleNumber = "51/2-b",
                            Description = "Hız sınırını %30'dan %50'ye kadar aşmak",
                            IsActive = true
                        },
                        new
                        {
                            Id = 4,
                            Amount = 1506.00m,
                            ArticleNumber = "73/c",
                            Description = "Seyir halinde cep telefonu kullanmak",
                            IsActive = true
                        },
                        new
                        {
                            Id = 5,
                            Amount = 6439.00m,
                            ArticleNumber = "48/5",
                            Description = "Alkollü araç kullanmak (1. Defa)",
                            IsActive = true
                        },
                        new
                        {
                            Id = 6,
                            Amount = 690.00m,
                            ArticleNumber = "78/1-a",
                            Description = "Emniyet kemeri bulundurmamak ve kullanmamak",
                            IsActive = true
                        },
                        new
                        {
                            Id = 7,
                            Amount = 1506.00m,
                            ArticleNumber = "34/a",
                            Description = "Muayenesi yapılmamış bir aracın trafiğe çıkarılması",
                            IsActive = true
                        },
                        new
                        {
                            Id = 8,
                            Amount = 690.00m,
                            ArticleNumber = "61/1-a",
                            Description = "Taşıt yolu üzerinde hatalı park etmek",
                            IsActive = true
                        },
                        new
                        {
                            Id = 9,
                            Amount = 32233.00m,
                            ArticleNumber = "67/1-d",
                            Description = "Drift atmak (Araçla tehlikeli hareketler yapmak)",
                            IsActive = true
                        },
                        new
                        {
                            Id = 10,
                            Amount = 6439.00m,
                            ArticleNumber = "26/2",
                            Description = "Araçlarda yetkisiz çakar veya siren kullanmak",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("trafficFineManager.Entities.Model", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Models");
                });

            modelBuilder.Entity("trafficFineManager.Entities.TrafficFine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatorUserId")
                        .HasColumnType("int");

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<int>("FineTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NotificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReceiptNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ViolationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ViolationReason")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ViolatorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ViolatorTC")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("CreatorUserId");

                    b.HasIndex("DistrictId");

                    b.HasIndex("FineTypeId");

                    b.HasIndex("VehicleId");

                    b.ToTable("TrafficFines");
                });

            modelBuilder.Entity("trafficFineManager.Entities.TrafficFineHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ActionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ActionType")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("NewStatus")
                        .HasColumnType("int");

                    b.Property<int?>("OldStatus")
                        .HasColumnType("int");

                    b.Property<int>("TrafficFineId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrafficFineId");

                    b.HasIndex("UserId");

                    b.ToTable("TrafficFineHistories");
                });

            modelBuilder.Entity("trafficFineManager.Entities.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ModelId")
                        .HasColumnType("int");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OwnerTC")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("VehicleType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("ModelId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("trafficFineManager.Entities.AppUser", b =>
                {
                    b.HasOne("trafficFineManager.Entities.AppRole", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("trafficFineManager.Entities.District", b =>
                {
                    b.HasOne("trafficFineManager.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("trafficFineManager.Entities.Model", b =>
                {
                    b.HasOne("trafficFineManager.Entities.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("trafficFineManager.Entities.TrafficFine", b =>
                {
                    b.HasOne("trafficFineManager.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("trafficFineManager.Entities.AppUser", "CreatorUser")
                        .WithMany()
                        .HasForeignKey("CreatorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("trafficFineManager.Entities.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("trafficFineManager.Entities.FineType", "FineType")
                        .WithMany()
                        .HasForeignKey("FineTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("trafficFineManager.Entities.Vehicle", "Vehicle")
                        .WithMany("TrafficFines")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("CreatorUser");

                    b.Navigation("District");

                    b.Navigation("FineType");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("trafficFineManager.Entities.TrafficFineHistory", b =>
                {
                    b.HasOne("trafficFineManager.Entities.TrafficFine", "TrafficFine")
                        .WithMany("Histories")
                        .HasForeignKey("TrafficFineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("trafficFineManager.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TrafficFine");

                    b.Navigation("User");
                });

            modelBuilder.Entity("trafficFineManager.Entities.Vehicle", b =>
                {
                    b.HasOne("trafficFineManager.Entities.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("trafficFineManager.Entities.Model", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("trafficFineManager.Entities.AppRole", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("trafficFineManager.Entities.TrafficFine", b =>
                {
                    b.Navigation("Histories");
                });

            modelBuilder.Entity("trafficFineManager.Entities.Vehicle", b =>
                {
                    b.Navigation("TrafficFines");
                });
#pragma warning restore 612, 618
        }
    }
}
