// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrafficFineApp.Data;

#nullable disable

namespace trafficFineManager.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260823095432_AddLocationEntities")]
    partial class AddLocationEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("trafficFineManager.Entities.AppRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Memur"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Yonetici"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Finansman"
                        });
                });

            modelBuilder.Entity("trafficFineManager.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IdentityNumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "ahmet@sirket.com",
                            FirstName = "Ahmet",
                            IdentityNumber = "11111111111",
                            LastName = "Memur",
                            PasswordHash = "123456",
                            RegistrationNumber = "S-001",
                            RoleId = 1
                        },
                        new
                        {
                            Id = 2,
                            Email = "ayse@sirket.com",
                            FirstName = "Ayşe",
                            IdentityNumber = "22222222222",
                            LastName = "Yönetici",
                            PasswordHash = "123456",
                            RegistrationNumber = "S-002",
                            RoleId = 2
                        },
                        new
                        {
                            Id = 3,
                            Email = "mehmet@sirket.com",
                            FirstName = "Mehmet",
                            IdentityNumber = "33333333333",
                            LastName = "Finans",
                            PasswordHash = "123456",
                            RegistrationNumber = "S-003",
                            RoleId = 3
                        });
                });

            modelBuilder.Entity("trafficFineManager.Entities.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Renault"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Ford"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Fiat"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Toyota"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Volkswagen"
                        });
                });

            modelBuilder.Entity("trafficFineManager.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "İstanbul"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Ankara"
                        });
                });

            modelBuilder.Entity("trafficFineManager.Entities.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Districts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            Name = "Kadıköy"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 1,
                            Name = "Beşiktaş"
                        },
                        new
                        {
                            Id = 3,
                            CityId = 1,
                            Name = "Şişli"
                        },
                        new
                        {
                            Id = 4,
                            CityId = 2,
                            Name = "Çankaya"
                        },
                        new
                        {
                            Id = 5,
                            CityId = 2,
                            Name = "Yenimahalle"
                        });
                });

            modelBuilder.Entity("trafficFineManager.Entities.FineType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ArticleNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("FineTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 1506m,
                            ArticleNumber = "47/1-b",
                            Description = "Kırmızı ışık kuralına uymamak",
                            IsActive = true
                        },
                        new
                        {
                            Id = 2,
                            Amount = 1506m,
                            ArticleNumber = "51/2-a",
                            Description = "Hız sınırını %10 - %30 aşmak",
                            IsActive = true
                        },
                        new
                        {
                            Id = 3,
                            Amount = 3135m,
                            ArticleNumber = "51/2-b",
                            Description = "Hız sınırını %30 - %50 aşmak",
                            IsActive = true
                        },
                        new
                        {
                            Id = 4,
                            Amount = 6439m,
                            ArticleNumber = "51/2-c",
                            Description = "Hız sınırını %50'den fazla aşmak",
                            IsActive = true
                        },
                        new
                        {
                            Id = 5,
                            Amount = 690m,
                            ArticleNumber = "78/1-a",
                            Description = "Emniyet kemeri takmamak",
                            IsActive = true
                        },
                        new
                        {
                            Id = 6,
                            Amount = 1506m,
                            ArticleNumber = "73/c",
                            Description = "Seyir halinde cep telefonu kullanmak",
                            IsActive = true
                        });
                });

            modelBuilder.Entity("trafficFineManager.Entities.Model", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.ToTable("Models");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            Name = "Clio"
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 1,
                            Name = "Megane"
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 2,
                            Name = "Transit"
                        },
                        new
                        {
                            Id = 4,
                            BrandId = 2,
                            Name = "Focus"
                        },
                        new
                        {
                            Id = 5,
                            BrandId = 3,
                            Name = "Egea"
                        },
                        new
                        {
                            Id = 6,
                            BrandId = 4,
                            Name = "Corolla"
                        },
                        new
                        {
                            Id = 7,
                            BrandId = 5,
                            Name = "Passat"
                        });
                });

            modelBuilder.Entity("trafficFineManager.Entities.TrafficFine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatorUserId")
                        .HasColumnType("int");

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<int>("FineTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("NotificationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReceiptNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ViolationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ViolationReason")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ViolatorName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ViolatorTC")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("CreatorUserId");

                    b.HasIndex("DistrictId");

                    b.HasIndex("FineTypeId");

                    b.HasIndex("VehicleId");

                    b.ToTable("TrafficFines");
                });

            modelBuilder.Entity("trafficFineManager.Entities.TrafficFineHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ActionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ActionType")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("NewStatus")
                        .HasColumnType("int");

                    b.Property<int?>("OldStatus")
                        .HasColumnType("int");

                    b.Property<int>("TrafficFineId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TrafficFineId");

                    b.HasIndex("UserId");

                    b.ToTable("TrafficFineHistories");
                });

            modelBuilder.Entity("trafficFineManager.Entities.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ModelId")
                        .HasColumnType("int");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OwnerTC")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int>("VehicleType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BrandId");

                    b.HasIndex("ModelId");

                    b.ToTable("Vehicles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BrandId = 1,
                            IsActive = true,
                            ModelId = 1,
                            OwnerName = "Ahmet Yılmaz",
                            OwnerTC = "11111111110",
                            PlateNumber = "34ABC123",
                            VehicleType = 1
                        },
                        new
                        {
                            Id = 2,
                            BrandId = 2,
                            IsActive = true,
                            ModelId = 3,
                            OwnerName = "ABC Rent A Car",
                            OwnerTC = "22222222220",
                            PlateNumber = "06XYZ987",
                            VehicleType = 4
                        },
                        new
                        {
                            Id = 3,
                            BrandId = 3,
                            IsActive = true,
                            ModelId = 5,
                            OwnerName = "Mehmet Demir",
                            OwnerTC = "33333333330",
                            PlateNumber = "35DEF456",
                            VehicleType = 1
                        });
                });

            modelBuilder.Entity("trafficFineManager.Entities.AppUser", b =>
                {
                    b.HasOne("trafficFineManager.Entities.AppRole", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("trafficFineManager.Entities.District", b =>
                {
                    b.HasOne("trafficFineManager.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("trafficFineManager.Entities.Model", b =>
                {
                    b.HasOne("trafficFineManager.Entities.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("trafficFineManager.Entities.TrafficFine", b =>
                {
                    b.HasOne("trafficFineManager.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("trafficFineManager.Entities.AppUser", "CreatorUser")
                        .WithMany()
                        .HasForeignKey("CreatorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("trafficFineManager.Entities.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("trafficFineManager.Entities.FineType", "FineType")
                        .WithMany()
                        .HasForeignKey("FineTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("trafficFineManager.Entities.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("CreatorUser");

                    b.Navigation("District");

                    b.Navigation("FineType");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("trafficFineManager.Entities.TrafficFineHistory", b =>
                {
                    b.HasOne("trafficFineManager.Entities.TrafficFine", "TrafficFine")
                        .WithMany("Histories")
                        .HasForeignKey("TrafficFineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("trafficFineManager.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TrafficFine");

                    b.Navigation("User");
                });

            modelBuilder.Entity("trafficFineManager.Entities.Vehicle", b =>
                {
                    b.HasOne("trafficFineManager.Entities.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("trafficFineManager.Entities.Model", "Model")
                        .WithMany()
                        .HasForeignKey("ModelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Brand");

                    b.Navigation("Model");
                });

            modelBuilder.Entity("trafficFineManager.Entities.AppRole", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("trafficFineManager.Entities.TrafficFine", b =>
                {
                    b.Navigation("Histories");
                });
#pragma warning restore 612, 618
        }
    }
}
